version: '3'

services:
   mariadb:
     image: mariadb:5.5
     port:
       - "3306:3306"
     volumes:
       - database_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: database_test
       MYSQL_USER: test
       MYSQL_PASSWORD: test@123
     
   web:
     depends_on:
       - mariadb
     build:
       context: .
     ports:
       - "8000:80"

volumes:
   database_data:

